---
# tasks file for ansible-role-deploy_aide

- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'

- name: Ensure the aide package is installed.
  ansible.builtin.package:
    name: "{{ daid_package_name }}"
    state: present
    update_cache: true

- name: Check if aide database exists.
  ansible.builtin.stat:
    path: "{{ daid_db_path }}/{{ daid_db_name }}"
  register: daid_db_exists
  changed_when: not daid_db_exists.stat.exists
  notify:
    - Initialise aide database
